import { Avatar } from "@mui/material";
import Head from "next/head";
import style from "./profile.module.css";

export default function MyProfile() {
  return (
    <div>
      <Head>
        <title>Page Profile</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className={style.title}>Votre profil</h1>

        <div className={style.user}>
          <Avatar className={style.avatar} />
          <h3 className={style.name}>Prénom Nom</h3>
        </div>

        <h2 className={style.title2}>informations personnelles</h2>

        <section className={style.form}>
          <div className={style.infos}>
            <p className={style.contacts}>
              prenom.nom@gmail.com
              <br />
              <br />
              06.76.06.76.06
              <br />
              <br />
              praticienatempo.com
            </p>
          </div>
        </section>

        <div className={style.reseaux}>
          <a href="https://fr-fr.facebook.com/" className={style.link}>
            <img
              src="../img/fb.png"
              alt="logo facebook"
              className={style.logos}
            />
            <p>@Sophrologue</p>
          </a>

          <a href="https://www.instagram.com/?hl=fr" className={style.link}>
            <img
              src="../img/insta.png"
              alt="logo instagram"
              className={style.logos}
            />
            <p>@Sophrologue</p>
          </a>
        </div>

        <div className={style.btn}>
          <button className={style.button}>Modifier le profil</button>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
