import { Avatar } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import style from "./profile.module.css";

export default function MyProfile() {
  return (
    <div>
      <Head>
        <title>Page Profile</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className={style.title}>Votre profil</h1>

        <div className={style.user}>
          <Avatar className={style.avatar} />
          <h3 className={style.name}>Prénom Nom</h3>
        </div>

        <h2 className={style.title2}>informations personnelles</h2>

        <section className={style.form}>
          <div className={style.infos}>
            <p className={style.contacts}>
              Prénom.nom@gmail.com
              <br />
              <br />
              06 76 06 76 06
              <br />
              <br />
              praticienatempo.com
            </p>
          </div>
        </section>

        <div className={style.reseaux}>
          <Link href="https://fr-fr.facebook.com/">
            <a className={style.link}>
              <Image
                width={43}
                height={43}
                src="/img/fb.png"
                alt="logo facebook"
              />
              <p className={style.lnk}>@Sophrologue</p>
            </a>
          </Link>

          <Link href="https://www.instagram.com/?hl=fr">
            <a className={style.link}>
              <Image
                width={43}
                height={43}
                src="/img/insta.png"
                alt="logo instagram"
              />
              <p className={style.lnk}>@Sophrologue</p>
            </a>
          </Link>
        </div>

        <div className={style.btn}>
          <button className={style.button}>Modifier le profil </button>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
